
services:
  # Servicio PHP (Laravel)
  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    container_name: laravel_php
    volumes:
      - ..:/var/www
    networks:
      - laravel

  # Servicio Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  # Servicio PostgreSQL
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: always
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  # Servicio Redis
  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
